version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    restart: on-failure
    command: ["/bin/sh", "-c", "./bin/run_app.sh"]
    volumes:
      - app_gomod_data:/go/pkg/mod
      - .:/src
    environment:
      - APP_HOST=0.0.0.0

volumes:
  app_gomod_data:
